---

- include: ubuntu.yml
  when: "ansible_distribution == 'Ubuntu'"
  tags:
    - common

- name: configure 30-dev sudoers
  lineinfile: dest=/etc/sudoers.d/developers owner=root group=root mode=0440
              line="%developers ALL=(ALL) NOPASSWD:ALL"
              state=present
              create=yes
              validate='visudo -cf %s'
  tags:
    - common

- name: Create admins group
  group: name=developers system=yes state=present
  tags:
    - common

- name: Create common user
  user: name="{{ common_user }}" password="{{ common_user_password }}" shell=/bin/bash groups=sudo,developers append=yes
  tags:
    - common
