---
language: python
python:
  - "3.7-dev"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip
  sonarcloud:
    organization: clayman74-github
    branches:
      - master

jobs:
  include:
    - stage: "test"
      name: "Test"
      script:
        - pip install tox
        - tox -- --pg-image=postgres:10-alpine
        - sonar-scanner
    - stage: "build"
      name: "Build"
      if: tag is present
      script:
        - docker build --build-arg app_version=$(TRAVIS_TAG) -t registry.clayman.pro/wallet .
        - docker tag registry.clayman.pro/wallet registry.clayman.pro/wallet:$(TRAVIS_TAG)
        - docker login -u $(DOCKER_USER) -p $(DOCKER_PASS) registry.clayman.pro
        - docker push registry.clayman.pro/wallet
