---
language: python
python:
  - "3.7-dev"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

jobs:
  include:
    - stage: "test"
      name: "Test"
      script:
        - pip install tox
        - tox -- --pg-image=postgres:10-alpine
    - stage: "build"
      name: "Build"
      if: tag IS present
      script:
        - make build
        - make publish
