---

- name: Set facts
  set_fact:
    project_root: "/home/{{ project_user }}/projects/{{ project_name }}/web"
    project_web: "/var/www/{{ project_name }}"

- name: Set project dist folder
  set_fact:
    project_dist: "{{ lookup('env', 'HOME')}}/{{ project_name }}/dist"
  when: "lookup('env', 'CIRCLECI')"

- name: Prepare distribution
  local_action: shell make clean-web && make dist-web chdir="../"

- name: Upload distribution files
  copy: src="{{ project_dist }}/web.tar.gz" dest="{{ project_web }}/web.tar.gz" owner="{{ project_user }}" group="{{ project_user }}"
  remote_user: "{{ project_user }}"
  sudo: True

- name: Extract web assets
  shell: tar -xzvf web.tar.gz chdir="{{ project_web }}"
  remote_user: "{{ project_user }}"
  sudo: True
