---

- name: Pull consul image
  shell: docker pull {{consul_image}}

- name: Check consul container exists
  shell: docker ps -a --filter="name={{consul_container}}$"
  register: containers

- name: Create consul container
  shell: docker create --name {{consul_container}} -p "8300:8300" -p "8400:8400" -p "8500:8500" -p "8600:53/udp" {{consul_image}} -server -bootstrap -advertise {% if environment == 'vagrant' %}{{ansible_eth1.ipv4.address}}{% else %}{{ansible_eth0.ipv4.address}}{% endif %}
  when: containers.stdout.find('{{consul_container}}') == -1

- name: Assemble supervisor config
  template: src=supervisor.conf dest=/etc/supervisor/conf.d/{{consul_container}}.conf

- name: Enable consul supervisor process
  supervisorctl: name={{consul_container}} state=restarted
