---

- name: Add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx' state=present

- name: Add sources nginx repo
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu/ {{ ansible_distribution_release }} nginx' state=present

- name: Add nginx repo key
  apt_key: url=http://nginx.org/packages/keys/nginx_signing.key state=present

- name: Install nginx from repo
  apt: name=nginx update_cache=yes state=installed

- name: Change nginx log folder permissions
  file: path=/var/log/nginx owner=nginx group=nginx recurse=yes state=directory

- name: Remove default
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: Copy nginx config
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Start nginx on boot
  service: name=nginx state=started enabled=yes

