version: '3'

networks:
  micro_backend:
    external: true

services:
  wallet:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3.9
        # [Choice] Install Node.js
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        # USER_UID: 1000
        # USER_GID: 1000
    command: sleep infinity
    dns: 192.168.2.3
    networks:
      - micro_backend
    volumes:
      - ..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh
