---

- name: Set project facts
  set_fact:
    project_root: "/home/{{ project_user }}/projects/{{ project_name }}/backups"

- name: Create project backups folder
  file: path="{{ project_root }}" state=directory owner="{{ project_user }}" group="{{ project_user }}"
  remote_user: "{{ project_user }}"
  sudo: True

- name: Create database backup
  shell: sudo docker run --rm --link {{ postgres_container }}:postgres -e PGPASSWORD="{{ project_db_password }}" {{ postgres_image }} pg_dump -h postgres -d {{ project_db_name }} -U {{ project_db_user }} | gzip > {{ ansible_date_time['date'] }}.gz chdir="{{ project_root }}"
  remote_user: "{{ project_user }}"
  sudo: True

- name: Fetch new backup
  fetch: src="{{ project_root }}/{{ ansible_date_time['date'] }}.gz" dest="../backups/" flat=yes
  remote_user: "{{ project_user }}"
  sudo: True