---

- name: Set project facts
  set_fact:
    project_root: "/home/{{ project_user }}/projects/{{ project_name }}"

- name: Set project dist folder
  set_fact:
    project_dist: "{{ lookup('env', 'HOME')}}/{{ project_name }}/dist"
  when: "lookup('env', 'CIRCLECI')"

- name: Prepare distribution
  local_action: shell make clean && make dist chdir="../"

- name: Get distribution version
  local_action: shell python setup.py --version chdir="../"
  register: project_version

- name: Upload new distribution
  copy: src="{{ project_dist }}/{{ project_name }}-{{ project_version.stdout }}.tar.gz" dest="{{ project_root }}/{{ project_name }}-{{ project_version.stdout }}.tar.gz" owner="{{ project_user }}" group="{{ project_user }}"
  remote_user: "{{ project_user }}"
  sudo: True

- name: Upload docker file
  copy: src="Dockerfile" dest="{{ project_root }}/Dockerfile" owner="{{ project_user }}" group="{{ project_user }}"
  remote_user: "{{ project_user }}"
  sudo: True

- name: Build app image
  shell: docker build -t {{ project_name }}:{{ project_version.stdout }} {{ project_root }}
  remote_user: "{{ project_user }}"
  sudo: True

- name: Check app container exists
  shell: docker ps -a --filter="name={{ project_name }}$"
  register: output
  remote_user: "{{ project_user }}"
  sudo: True

- name: Remove existed app container
  shell: docker rm -f {{ project_name }}
  when: output.stdout.find('{{ project_name }}') != -1
  remote_user: "{{ project_user }}"
  sudo: True

- name: Create app container
  shell: docker create --name {{ project_name }} --link postgres:postgres -p 5000:5000 --restart=always {{ project_name }}:{{ project_version.stdout }}
  remote_user: "{{ project_user }}"
  sudo: True

- name: Start app container
  shell: docker start {{ project_name }}
  remote_user: "{{ project_user }}"
  sudo: True

- name: Make app db migrations
  shell: docker exec {{ project_name }} {{ project_name }} --config=/root/config.yml db upgrade head
  remote_user: "{{ project_user }}"
  sudo: True
