FROM {{ app_base_image }}

# Install required packages
RUN apk add --update --no-cache make libc-dev python3-dev linux-headers gcc

# Copy application distribution package
COPY {{ app_name }}-{{ app_version }}.tar.gz /root/

# Install application package
RUN pip install --no-cache-dir -U pip && pip install --no-cache-dir /root/{{ app_name }}-{{ app_version }}.tar.gz

EXPOSE {{ app_server_port }}

CMD ["{{ app_name }}", "server", "run", "--host=0.0.0.0", "--port={{ app_server_port }}", "--consul"]
